# Generated by Django 3.2.18 on 2023-04-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogapp', '0002_yoga_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
