# Generated by Django 3.2.18 on 2023-04-20 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yogapp', '0003_remove_comment_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yoga_email',
            new_name='YogaEmail',
        ),
    ]
